name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [staffflow-core, mobile-app, admin-panel, dev-tools, messaging-module]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        if [ -d "./apps/${{ matrix.app }}" ]; then
          npm install
        else
          echo "Directory ./apps/${{ matrix.app }} does not exist. Skipping..."
        fi
      working-directory: ./apps/${{ matrix.app }}

    - name: Check and Update ESLint Version
      run: |
        REQUIRED_VERSION="8.42.0"
        INSTALLED_VERSION=$(npx eslint -v | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+')
        if [ "$INSTALLED_VERSION" != "$REQUIRED_VERSION" ]; then
          echo "ESLint version mismatch. Updating to version $REQUIRED_VERSION..."
          npm install eslint@$REQUIRED_VERSION --save-dev
        else
          echo "ESLint version is up-to-date."
        fi
      working-directory: ./apps/${{ matrix.app }}

    - name: Check and Update Prettier Version
      run: |
        REQUIRED_VERSION="2.8.8"
        INSTALLED_VERSION=$(npx prettier -v)
        if [ "$INSTALLED_VERSION" != "$REQUIRED_VERSION" ]; then
          echo "Prettier version mismatch. Updating to version $REQUIRED_VERSION..."
          npm install prettier@$REQUIRED_VERSION --save-dev
        else
          echo "Prettier version is up-to-date."
        fi
      working-directory: ./apps/${{ matrix.app }}

    - name: Install Missing Lint or Test Scripts
      run: |
        if ! npm run | grep -q "lint"; then
          echo "Lint script not found. Installing default lint config..."
          npm set-script lint "eslint . --fix"
        fi
        if ! npm run | grep -q "test"; then
          echo "Test script not found. Installing default test config..."
          npm set-script test "jest"
          npm install jest --save-dev
        fi
      working-directory: ./apps/${{ matrix.app }}

    - name: Run Lint
      run: npm run lint
      working-directory: ./apps/${{ matrix.app }}

    - name: Run Tests
      run: npm run test
      working-directory: ./apps/${{ matrix.app }}
