name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [staffflow-core, mobile-app, admin-panel, dev-tools, messaging-module]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        # Check if the directory exists before running npm install
        if [ -d "./apps/${{ matrix.app }}" ]; then
          npm install
        else
          echo "Directory ./apps/${{ matrix.app }} does not exist. Skipping..."
        fi
      working-directory: ./apps/${{ matrix.app }}

    - name: Run Lint
      run: |
             - name: ESLint Code Lint & Fix
  # You may pin to the exact commit or the version.
  # uses: permafrost-dev/eslint-docker-ga@0611438792291217c8c826957841d6aba36cfb99
  uses: permafrost-dev/eslint-docker-ga@v1.0.0
                 # Check if the lint script exists before running
        if npm run | grep -q "lint"; then
          npm run lint
        else
          echo "Lint script not found. Skipping..."
        fi
      working-directory: ./apps/${{ matrix.app }}

    - name: Run Tests
      run: |
        # Check if the test script exists before running
        if npm run | grep -q "test"; then
          npm run test
        else
          echo "Test script not found. Skipping..."
        fi
      working-directory: ./apps/${{ matrix.app }}
