name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [staffflow-core, mobile-app, admin-panel, dev-tools, messaging-module]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        if [ -d "./apps/${{ matrix.app }}" ]; then
          npm install
        else
          echo "Directory ./apps/${{ matrix.app }} does not exist. Skipping..."
        fi
      working-directory: ./apps/${{ matrix.app }}

    - name: Ensure ESLint and Prettier Versions
      run: |
        npm install eslint@8.42.0 --save-dev
        npm install prettier@2.8.8 --save-dev
      working-directory: ./apps/${{ matrix.app }}

    - name: Install Missing Lint or Test Scripts
      run: |
        if ! npm](#)

